name: Build basic

on:
  pull_request:
  push:
    branches:
      - main


concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:

  build-push-image:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        id: push
        with:
          context: .
          file: ./docker/contract-verifier/Dockerfile
          push: false
          platforms: 'linux/amd64,linux/arm64'
          cache-from: type=gha,scope=basic
          cache-to: type=gha,mode=max,scope=basic
          tags: ghcr.io/${{ github.repository }}-basic:latest
