name: Deploy docs

on:
  push:
    branches:
      - "main"
    tags:
      - "core-v*.*.*"
      - "prover-v*.*.*"
    paths:
      - 'docs/**'
      - 'prover/docs/**'
      - '.github/workflows/deploy-docs.yaml'

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:

  get-changed-files:
    runs-on: ubuntu-latest
    outputs:
      core_any_changed: ${{ steps.changed-files.outputs.core_any_changed }}
      prover_any_changed: ${{ steps.changed-files.outputs.prover_any_changed }}
      ci_any_changed: ${{ steps.changed-files.outputs.ci_any_changed }}
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@c3a1bb2c992d77180ae65be6ae6c166cf40f857c # v45
        with:
          files_yaml: |
            prover:
              - 'prover/docs/**'
            core:
              - 'docs/**'
            ci:
              - '.github/workflows/deploy-docs.yml'

  deploy-core-docs:
    needs: get-changed-files
    runs-on: ubuntu-latest
    if: ${{ needs.get-changed-files.outputs.core_any_changed == 'true' || needs.get-changed-files.outputs.ci_any_changed == 'true' || startsWith(github.ref, 'refs/tags/core-v') }}
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Deploy core docs
        uses: matter-labs/deploy-mdbooks@fbbaab13c89782ff79b8b5fd2aa17d5540f41830 # v1
        with:
          version: ${{ github.ref_name }}
          docs-dir: 'docs'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          enable-tests: false # disable tests for now until fixed
          project: core

  deploy-prover-docs:
    needs: [get-changed-files, deploy-core-docs]
    # Special condition to run jobs consequentially
    if: |
      always() &&
      (needs.deploy-core-docs.result == 'success' || needs.deploy-core-docs.result == 'skipped') &&
      (needs.get-changed-files.outputs.prover_any_changed == 'true' || needs.get-changed-files.outputs.ci_any_changed == 'true' || startsWith(github.ref, 'refs/tags/prover-v'))
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Deploy prover docs
        uses: matter-labs/deploy-mdbooks@fbbaab13c89782ff79b8b5fd2aa17d5540f41830 # v1
        with:
          version: ${{ github.ref_name }}
          docs-dir: 'prover/docs'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          enable-tests: false # disable tests for now until fixed
          project: prover
