name: Release-plz

permissions:
  pull-requests: write
  contents: write

on:
  push:
    branches:
      - main

jobs:

  release:
    uses: matter-labs/era-compiler-ci/.github/workflows/release-plz.yaml@v1
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
      cargo_registry_token: ${{ secrets.CRATES_IO_TOKEN }}

  # - name: Send Release Info
  #   if: ${{ steps.release.outputs.releases_created == 'true' }}
  #   uses: matter-labs/format-release-please-for-slack-action@69e6fe9e4ec531b7b5fb0d826f73c190db83cf42 # v2.1.0
  #   with:
  #     release-please-output: ${{ toJSON(steps.release.outputs) }}
  #     slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_RELEASES }}